<a href="https://colab.research.google.com/github/pathilink/adyen_payment_optimization_case/blob/main/notebooks/01_data_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='#0ABF56'>Optimisation Data Analyst Case Study </font>

## <font color='#0ABF56'> 01 - Data Loading </font>

# Libraries

In [1]:
import pandas as pd
# import numpy as np
# import datetime
# import seaborn as sns
# from matplotlib import pyplot as plt

# Data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/test/adyen/data/raw/DataAnalyst_case_study_data.csv')

df.head()

,psp_reference,bin,scheme,issuername,shopper_interaction,avs_data_supplied,cvc_data_supplied,currency_code,amount,raw_acquirer_response,creation_date,received,authorization
0,1,400178.0,visa,BANCO DO BRASIL S.A.,Ecommerce,No,No,BRL,1,05 : Do not honor / A201 : 3D Secure Mandated,6/1/19 0:19,1,0
1,2,486348.0,visa,FIRST ATLANTIC BANK LIMITED,Ecommerce,No,No,BRL,6.48,00 : Approved or completed successfully,6/1/19 0:22,1,1
2,3,482481.0,visa,ITAU UNIBANCO S.A.,Ecommerce,No,Yes,BRL,4,06 : Error,6/1/19 0:46,1,0
3,4,439267.0,visa,CAIXA ECONOMICA FEDERAL,Ecommerce,No,Yes,BRL,2.76,05 : Do not honor / A201 : 3D Secure Mandated,6/1/19 1:02,1,0
4,5,489347.0,visa,VTB BANK PJSC,Ecommerce,No,Yes,BRL,97,00 : Approved or completed successfully,6/1/19 1:30,1,1

# Check

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 933387 entries, 0 to 933386
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   psp_reference          933387 non-null  int64
 1   bin                    933376 non-null  float64
 2   scheme                 933387 non-null  object
 3   issuername             932580 non-null  object
 4   shopper_interaction    933387 non-null  object
 5   avs_data_supplied      933387 non-null  object
 6   cvc_data_supplied      933387 non-null  object
 7   currency_code          933387 non-null  object
 8   amount                 933387 non-null  object
 9   raw_acquirer_response  933387 non-null  object
 10  creation_date          933387 non-null  object
 11  received               933387 non-null  int64
 12  authorization          933387 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 92.6+ MB

### unique

In [5]:
# list unique values per column
value_list = []
unique_list = []

for col in df:
  value_list.append(col)
  unique_list.append(df[col].unique())

# list(zip(col_list, unique_list))
df_unique = pd.DataFrame(
    {'column': value_list,
     'nunique': unique_list
     }
)

df_unique

                   column                                            nunique
0           psp_reference  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
1                     bin  [400178.0, 486348.0, 482481.0, 439267.0, 48934...
2                  scheme                                         [visa, mc]
3              issuername  [BANCO DO BRASIL S.A., FIRST ATLANTIC BANK LIM...
4     shopper_interaction                              [Ecommerce, ContAuth]
5       avs_data_supplied                                          [No, Yes]
6       cvc_data_supplied                                          [No, Yes]
7           currency_code                                              [BRL]
8                  amount  [1, 6.48, 4, 2.76, 97, 2.8, 66.4, 2.56, 2.44, ...
9   raw_acquirer_response  [05 : Do not honor / A201 : 3D Secure Mandated...
10          creation_date  [6/1/19 0:19, 6/1/19 0:22, 6/1/19 0:46, 6/1/19...
11               received                                                [1]
12          authorization                                             [0, 1]

In [6]:
# unique key
df['psp_reference'].is_unique

True

In [7]:
df['bin'].nunique()

2598

In [8]:
df['issuername'].nunique()

722

### nulls

In [9]:
# missing data
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data

                       Total   Percent
issuername               807  0.000865
bin                       11  0.000012
psp_reference              0  0.000000
scheme                     0  0.000000
shopper_interaction        0  0.000000
avs_data_supplied          0  0.000000
cvc_data_supplied          0  0.000000
currency_code              0  0.000000
amount                     0  0.000000
raw_acquirer_response      0  0.000000
creation_date              0  0.000000
received                   0  0.000000
authorization              0  0.000000

#### issuername

In [10]:
issuername_na = df.query('issuername.isna()')['bin'].unique().tolist()
issuername_na[:10]

[473702.0,
 465123.0,
 465098.0,
 434256.0,
 491628.0,
 526165.0,
 479407.0,
 411111.0,
 557425.0,
 480761.0]

In [11]:
# issuername availability depends strictly on the bin
df.query('bin in @issuername_na & issuername.notna()')[:20]

Empty DataFrame
Columns: [psp_reference, bin, scheme, issuername, shopper_interaction, avs_data_supplied, cvc_data_supplied, currency_code, amount, raw_acquirer_response, creation_date, received, authorization]
Index: []

In [12]:
df.query('bin in @issuername_na')[:10]

,psp_reference,bin,scheme,issuername,shopper_interaction,avs_data_supplied,cvc_data_supplied,currency_code,amount,raw_acquirer_response,creation_date,received,authorization
148,149,473702.0,visa,NaN,Ecommerce,No,Yes,BRL,197,05 : Do not honor,6/10/19 3:24,1,0
164,165,473702.0,visa,NaN,Ecommerce,No,No,BRL,65.13,05 : Do not honor,6/11/19 1:56,1,0
165,166,473702.0,visa,NaN,Ecommerce,No,No,BRL,62.03,05 : Do not honor,6/11/19 2:00,1,0
182,183,465123.0,visa,NaN,ContAuth,No,No,BRL,69,00 : Approved or completed successfully,6/12/19 17:10,1,1
227,228,465098.0,visa,NaN,ContAuth,No,No,BRL,25.2,00 : Approved or completed successfully,6/15/19 1:50,1,1
279,280,465123.0,visa,NaN,ContAuth,No,No,BRL,18.99,00 : Approved or completed successfully,6/17/19 1:20,1,1
302,303,473702.0,visa,NaN,Ecommerce,No,No,BRL,93.15,00 : Approved or completed successfully,6/18/19 0:40,1,1
414,415,473702.0,visa,NaN,ContAuth,No,No,BRL,75.8,05 : Do not honor,6/22/19 23:00,1,0
434,435,473702.0,visa,NaN,Ecommerce,No,No,BRL,30.78,05 : Do not honor,6/23/19 18:55,1,0
460,461,434256.0,visa,NaN,Ecommerce,No,No,BRL,321.9,05 : Do not honor,6/24/19 20:13,1,0

💡

Issuer name missingness is systematic rather than random, as all null issuer values are consistently associated with the same BINs. This suggests a BIN enrichment or reference-mapping limitation, rather than incomplete transaction-level data.

#### bin

In [13]:
df.query('bin.isna()')

,psp_reference,bin,scheme,issuername,shopper_interaction,avs_data_supplied,cvc_data_supplied,currency_code,amount,raw_acquirer_response,creation_date,received,authorization
144840,144841,NaN,mc,NaN,Ecommerce,No,Yes,BRL,478.8,14 : Invalid card number,6/23/19 21:26,1,0
178053,178054,NaN,mc,NaN,Ecommerce,No,Yes,BRL,0,14 : Invalid card number,6/25/19 4:23,1,0
249337,249338,NaN,visa,NaN,Ecommerce,No,Yes,BRL,169.47,Invalid CardNumber - PAN length mismatch.,6/30/19 21:27,1,0
292667,292668,NaN,visa,NaN,Ecommerce,No,Yes,BRL,3.32,Invalid CardNumber - PAN length mismatch.,6/14/19 22:17,1,0
342798,342799,NaN,visa,NaN,Ecommerce,No,Yes,BRL,4.96,Invalid CardNumber - PAN length mismatch.,6/30/19 19:40,1,0
384603,384604,NaN,visa,NaN,Ecommerce,No,Yes,BRL,213.15,Invalid CardNumber - PAN length mismatch.,6/13/19 0:51,1,0
402992,402993,NaN,visa,NaN,Ecommerce,No,Yes,BRL,490.08,Invalid CardNumber,6/29/19 2:27,1,0
426593,426594,NaN,visa,NaN,Ecommerce,No,Yes,BRL,1.76,Invalid CardNumber - PAN length mismatch.,6/24/19 18:32,1,0
498723,498724,NaN,visa,NaN,Ecommerce,No,Yes,BRL,3.88,Invalid CardNumber - PAN length mismatch.,6/30/19 19:40,1,0
624700,624701,NaN,visa,NaN,Ecommerce,No,Yes,BRL,0,Invalid CardNumber - PAN length mismatch.,6/2/19 23:37,1,0
828056,828057,NaN,visa,NaN,Ecommerce,No,Yes,BRL,799,Invalid CardNumber - PAN length mismatch.,6/23/19 6:16,1,0

💡

A subset of declined ecommerce transactions consistently presents null BIN and issuer information, while still containing Visa or Mastercard scheme identification, supplied CVC data, no AVS/address data, and the acquirer response ‘invalid card number’.

This pattern suggests that these payments fail during the initial card validation stage, before reaching issuer-level authorization or any downstream optimization opportunities. The absence of BIN and issuer data indicates that the submitted card number could not be successfully validated or identified.

The most likely drivers are shopper card-entry errors, such as mistyped or incomplete card numbers, and potential automated card testing activity, where invalid card credentials are systematically submitted in ecommerce environments. Because these transactions fail prior to authorization processing, they are not recoverable through authorization optimization strategies such as routing or retry logic.

### count

In [14]:
def summarize_columns(df, top_n=10):
    # filter
    cols = df.select_dtypes(include=['object', 'category']).columns

    for col in cols:
        print(f"📌 {col.upper()}")
        counts = df[col].value_counts().head(top_n)
        for val, count in counts.items():
            print(f"  - {val}: {count}")
        print("-" * 30)

summarize_columns(df)

📌 SCHEME
  - mc: 618722
  - visa: 314665
------------------------------
📌 ISSUERNAME
  - ITAU UNIBANCO S.A.: 199821
  - NU PAGAMENTOS SA: 159244
  - BANCO SANTANDER (BRASIL) S.A.: 123232
  - BANCO BRADESCO S.A.: 82630
  - BANCO DO BRASIL S.A.: 75933
  - BANCO ITAUCARD S.A.: 57072
  - BANCO SANTANDER S.A.: 31029
  - CAIXA ECONOMICA FEDERAL: 24795
  - BANCO DO BRASIL, S.A.: 17757
  - BANCO BRADESCARD S.A.: 17462
------------------------------
📌 SHOPPER_INTERACTION
  - Ecommerce: 505341
  - ContAuth: 428046
------------------------------
📌 AVS_DATA_SUPPLIED
  - No: 924773
  - Yes: 8614
------------------------------
📌 CVC_DATA_SUPPLIED
  - No: 659425
  - Yes: 273962
------------------------------
📌 CURRENCY_CODE
  - BRL: 933387
------------------------------
📌 AMOUNT
  - 19: 25491
  - 12: 22572
  - 1: 18203
  - 20: 7550
  - 2: 7172
  - 3: 5600
  - 16.9: 5425
  - 478.8: 5068
  - 5: 4828
  - 8: 4765
------------------------------
📌 RAW_ACQUIRER_RESPONSE
  - 00 : Approved or completed successfully: 737545
  - 05 : Do not honor: 59794
  - 51 : Insufficient funds/over credit limit: 53426
  - 62 : Restricted card: 26084
  - 57 : Transaction not permitted to issuer/cardholder: 18087
  - 06 : Error: 7868
  - 14 : Invalid card number: 7172
  - 05 : Do not honor / A201 : 3D Secure Mandated: 5221
  - 85 : No reason to decline a request for account number verification, address verification, CVV2 verification, or a credit voucher or merchandise return: 2671
  - 63 : Security violation: 2537
------------------------------
📌 CREATION_DATE
  - 6/22/19 11:01: 1016
  - 6/25/19 11:31: 978
  - 6/24/19 11:03: 974
  - 6/27/19 11:31: 781
  - 6/30/19 11:01: 753
  - 6/29/19 11:01: 633
  - 6/30/19 11:02: 633
  - 6/28/19 11:01: 547
  - 6/23/19 11:31: 524
  - 6/17/19 11:01: 458
------------------------------

In [15]:
df['creation_date'].astype('datetime64[ns]').dt.date.value_counts().sort_index()

creation_date
2019-06-01    26834
2019-06-02    25108
2019-06-03    22242
2019-06-04    20519
2019-06-05    22070
2019-06-06    23859
2019-06-07    24535
2019-06-08    26228
2019-06-09    26626
2019-06-10    24429
2019-06-11    20710
2019-06-12    25080
2019-06-13    24862
2019-06-14    26686
2019-06-15    28813
2019-06-16    28688
2019-06-17    25569
2019-06-18    26197
2019-06-19    27555
2019-06-20    18967
2019-06-21    14210
2019-06-22    35791
2019-06-23    49467
2019-06-24    46790
2019-06-25    44794
2019-06-26    49908
2019-06-27    49562
2019-06-28    51765
2019-06-29    47735
2019-06-30    47788
Name: count, dtype: int64